language: rust
sudo: false

addons:
  apt:
    packages:
      - curl
      - build-essential
      - wget
      - unzip
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - tree
      - clang

env:
  CXX: clang
  CC: clang

before_script:
  - "cd /tmp ; wget https://github.com/Itseez/opencv/archive/2.4.11.zip ; unzip 2.4.11.zip ; mv opencv-2.4.11 opencv"
  - "cd /tmp/opencv ; mkdir release ; cd release ; cmake -D CMAKE_BUILD_TYPE=RELEASE .. ; make -j && tree ."

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
