language: rust
sudo: false

addons:
  apt:
    packages:
      - curl
      - build-essential
      - wget
      - unzip
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - tree
      - clang

env:
  CXX: clang
  CC: clang
  PKG_CONFIG_PATH: /tmp/opencv/release/unix-install

before_script:
  - pwd
  - "if [ ! -e /tmp/opencv ] ; then cd /tmp ; wget https://github.com/Itseez/opencv/archive/2.4.11.zip ; unzip 2.4.11.zip ; mv opencv-2.4.11 opencv ; cd /tmp/opencv ; mkdir release install; cd release ; cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF -D CMAKE_INSTALL_PREFIX=/tmp/opencv/install .. ; make install ; fi"
  - cd /home/travis/build/kali/opencv-rust
  - pkg-config --cflags opencv
  - pkg-config --libs opencv
  - tree /tmp/opencv/

cache:
  directories:
    - /tmp/opencv

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
