language: rust
rust:
  - stable
  - beta
  - nightly

cache:
  timeout: 600
  cargo: true
  ccache: true
  directories:
    - $HOME/build/opencv

sudo: true
dist: xenial

addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - wget
      - cmake
      - libgtk2.0-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libavresample-dev
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libwebp-dev
      - libopenexr-dev
      - libdc1394-22-dev
      - libatlas-base-dev
      - liblapacke-dev
      - libeigen3-dev
      - tree

env:
  global:
    - Atlas_ROOT_DIR=/usr/include/ # for cmake to find lapacke.h
    - LC_CTYPE=C.UTF-8 # makes python3 locale.getpreferredencoding() return utf8 encoding instead of ansi
  matrix:
    - OPENCV_VERSION=3.2.0 OPENCV_PKGCONFIG=opencv CARGO_FEATURES=opencv-32
    - OPENCV_VERSION=3.4.6 OPENCV_PKGCONFIG=opencv CARGO_FEATURES=opencv-34
    - OPENCV_VERSION=4.1.0 OPENCV_PKGCONFIG=opencv4 CARGO_FEATURES=opencv-41

before_script:
  - ci/install-opencv.sh
  - pkg-config --cflags $OPENCV_PKGCONFIG
  - pkg-config --libs $OPENCV_PKGCONFIG

script:
  - cargo test --verbose --no-default-features --features $CARGO_FEATURES

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
