language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

sudo: true
dist: xenial

addons:
  apt:
    packages:
      - wget
      - unzip
      - build-essential
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - tree

env:
#  global:
#    - DOC=3.1.0
  matrix:
    - OPENCV_VERSION=3.4.6

before_script:
  - |
    if [ ! -e /tmp/opencv/opencv-$OPENCV_VERSION/release/unix-install ]
    then
      mkdir -p /tmp/opencv
      cd /tmp/opencv
      rm -rf opencv-$OPENCV_VERSION
      wget -q https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip
      unzip -q $OPENCV_VERSION.zip
      cd opencv-$OPENCV_VERSION
      mkdir release install
      cd release
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DINSTALL_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/tmp/opencv/opencv-$OPENCV_VERSION/install ..
      make -j4 install
    fi
  - tree /tmp/opencv/opencv-$OPENCV_VERSION/release
  - export PKG_CONFIG_PATH=/tmp/opencv/opencv-$OPENCV_VERSION/release/unix-install
  - pkg-config --cflags opencv
  - pkg-config --libs opencv
  - gcc --version
  - cd /home/travis/build/twistedfall/opencv-rust

#after_success:
#  - echo $TRAVIS_RUST_VERSION
#  - |
#    if [ "$OPENCV_VERSION" = "$DOC" -a "$TRAVIS_RUST_VERSION" = "stable" ]
#    then
#      cargo doc
#      curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
#    fi

#cache:
#  directories:
#    - /tmp/opencv

matrix:
  allow_failures:
    - rust: nightly
#  include:
#    - rust: stable
#      env: OPENCV_VERSION=2.4.10
