os:
  - linux
  - windows
  - osx

sudo: true
dist: bionic
osx_image: xcode11.2

cache:
  timeout: 600
  cargo: false
  directories:
    - $HOME/build/opencv

language: rust
rust:
  - stable
  - beta
#  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - os: linux
      env: OPENCV_VERSION=3.2.0 OPENCV_PKGCONFIG=opencv CARGO_FEATURES=opencv-32
      rust: stable

env:
  global:
    - Atlas_ROOT_DIR=/usr/include/ # for cmake to find lapacke.h
    - LC_CTYPE=C.UTF-8 # makes python3 locale.getpreferredencoding() return utf8 encoding instead of ansi
  matrix:
    - OPENCV_VERSION=3.4.8 WIN_OPENCV_VERSION=3.4.7 OSX_OPENCV_VERSION=@3 OPENCV_PKGCONFIG=opencv CARGO_FEATURES=opencv-34
    - OPENCV_VERSION=4.1.2 WIN_OPENCV_VERSION=4.1.1 OSX_OPENCV_VERSION= OPENCV_PKGCONFIG=opencv4 CARGO_FEATURES=opencv-41

addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - wget
      - cmake
      - libatlas-base-dev
      - libavcodec-dev
      - libavformat-dev
      - libavresample-dev
      - libceres-dev
      - libdc1394-22-dev
      - libeigen3-dev
      - libfreetype6-dev
      - libgdal-dev
      - libgflags-dev
      - libgoogle-glog-dev
      - libgphoto2-dev
      - libgstreamer-plugins-base1.0-dev
      - libharfbuzz-dev
      - libhdf5-dev
      - libjpeg-dev
      - liblapacke-dev
      - libleptonica-dev
      - libopenexr-dev
      - libpng-dev
      - libswscale-dev
      - libtbb-dev
      - libtesseract-dev
      - libtiff-dev
      - libvtk7-dev
      - libwebp-dev
      - qtbase5-dev
      - tree

install:
  - ci/install.sh

script:
  - ci/script.sh
