language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

sudo: true
dist: xenial

addons:
  apt:
    packages:
      - unzip
      - build-essential
      - cmake
      - libgtk2.0-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libavresample-dev
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libwebp-dev
      - libopenexr-dev
      - libdc1394-22-dev
      - libatlas-base-dev
      - liblapacke-dev
      - libeigen3-dev
      - python-dev
      - python-numpy
      - tree

env:
  global:
    - OPENCV_VERSION=3.4.6
    - Atlas_ROOT_DIR=/usr/include/ # for cmake to find lapacke.h

before_script:
  - wget -O- https://github.com/opencv/opencv/archive/$OPENCV_VERSION.tar.gz | tar -xzC ~/build
  - wget -O- https://github.com/opencv/opencv_contrib/archive/$OPENCV_VERSION.tar.gz | tar -xzC ~/build
  - mkdir -p ~/build/opencv-$OPENCV_VERSION-build
  - pushd ~/build/opencv-$OPENCV_VERSION-build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DINSTALL_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=ALL -DWITH_IPP=OFF -DPYTHON_EXECUTABLE=OFF -DINSTALL_PYTHON_EXAMPLES=OFF -DWITH_LAPACK=ON -DWITH_EIGEN=ON -DBUILD_SHARED_LIBS=ON -DWITH_TBB=ON -DOPENCV_ENABLE_NONFREE=ON -DCMAKE_INSTALL_PREFIX=/usr -DOPENCV_EXTRA_MODULES_PATH=~/build/opencv_contrib-$OPENCV_VERSION/modules ~/build/opencv-$OPENCV_VERSION
  - sudo make -j4 install
  - tree .
  - popd
  - pkg-config --cflags opencv
  - pkg-config --libs opencv

matrix:
  allow_failures:
    - rust: nightly
