language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

sudo: true
dist: xenial

addons:
  apt:
    packages:
      - wget
      - unzip
      - build-essential
      - cmake
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libavresample-dev
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libwebp-dev
      - libopenexr-dev
      - libdc1394-22-dev
      - libatlas-base-dev
      - liblapacke-dev
      - libeigen3-dev
      - python-dev
      - python-numpy
      - tree

env:
  matrix:
    - OPENCV_VERSION=3.4.6

before_script:
  - |
    if [ ! -e /tmp/opencv/opencv-$OPENCV_VERSION/release/unix-install ]
    then
      mkdir -p /tmp/opencv
      cd /tmp/opencv
      rm -rf opencv-$OPENCV_VERSION
      wget -q https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip
      unzip -q $OPENCV_VERSION.zip
      cd opencv-$OPENCV_VERSION
      mkdir release install
      cd release
      Atlas_ROOT_DIR=/usr/include/ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DINSTALL_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps= -DWITH_IPP=OFF -DPYTHON_EXECUTABLE=OFF -DINSTALL_PYTHON_EXAMPLES=OFF -DWITH_LAPACK=ON -DWITH_EIGEN=ON -DBUILD_SHARED_LIBS=ON -DWITH_TBB=ON -D OPENCV_ENABLE_NONFREE=ON -DCMAKE_INSTALL_PREFIX=/usr ..
      sudo make -j4 install
    fi
  - tree /tmp/opencv/opencv-$OPENCV_VERSION/release
  - pkg-config --cflags opencv
  - pkg-config --libs opencv
  - gcc --version
  - cd /home/travis/build/twistedfall/opencv-rust

matrix:
  allow_failures:
    - rust: nightly
