language: rust
rust:
  - stable
  - beta
  - nightly

cache:
  timeout: 600
  cargo: true
  ccache: true
  directories:
    - $HOME/build/opencv

sudo: true
dist: xenial

addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - wget
      - cmake
      - libgtk2.0-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libavresample-dev
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libwebp-dev
      - libopenexr-dev
      - libdc1394-22-dev
      - libatlas-base-dev
      - liblapacke-dev
      - libeigen3-dev
      - tree

env:
  global:
    - Atlas_ROOT_DIR=/usr/include/ # for cmake to find lapacke.h
    - LC_CTYPE=C.UTF-8 # makes python3 locale.getpreferredencoding() return utf8 encoding instead of ansi
  matrix:
    - OPENCV_VERSION=3.4.6 OPENCV_PKGCONFIG=opencv
    - OPENCV_VERSION=4.1.0 OPENCV_PKGCONFIG=opencv4

before_script:
  - mkdir -p ~/build/opencv
  - wget -O- https://github.com/opencv/opencv/archive/$OPENCV_VERSION.tar.gz | tar -xzC ~/build/opencv
  - wget -O- https://github.com/opencv/opencv_contrib/archive/$OPENCV_VERSION.tar.gz | tar -xzC ~/build/opencv
  - mkdir -p ~/build/opencv/opencv-$OPENCV_VERSION-build
  - pushd ~/build/opencv/opencv-$OPENCV_VERSION-build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DOPENCV_GENERATE_PKGCONFIG=ON -DOPENCV_ENABLE_NONFREE=ON -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DINSTALL_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DPYTHON_EXECUTABLE=OFF -DINSTALL_PYTHON_EXAMPLES=OFF -DBUILD_opencv_apps=ALL -DWITH_LAPACK=ON -DWITH_EIGEN=ON -DWITH_TBB=ON -DWITH_ADE=OFF -DCMAKE_INSTALL_PREFIX=/usr -DOPENCV_EXTRA_MODULES_PATH=~/build/opencv/opencv_contrib-$OPENCV_VERSION/modules ~/build/opencv/opencv-$OPENCV_VERSION
  - sudo make -j4 install
  - tree .
  - popd
  - pkg-config --cflags $OPENCV_PKGCONFIG
  - pkg-config --libs $OPENCV_PKGCONFIG

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
