[package]
name = "opencv"
description = "Rust bindings for OpenCV"
documentation = "https://docs.rs/opencv"
repository = "https://github.com/twistedfall/opencv-rust"
readme = "README.md"
keywords = [ "opencv", "vision" ]
license = "MIT"
version = "0.7.2"
edition = "2018"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
build = "build.rs"

[badges]
travis-ci = { repository = "twistedfall/opencv-rust", branch = "master" }

[dependencies]
lazy_static = "1.0"
libc = "0.2"
slab = "0.4"

[build-dependencies]
pkg-config = "0.3.14"
cc = "1.0"
glob = "0.3"

[features]
buildtime_bindgen = []
