[package]
name = "opencv"
description = "Rust bindings for OpenCV"
documentation = "https://docs.rs/opencv"
repository = "https://github.com/twistedfall/opencv-rust"
readme = "README.md"
keywords = ["opencv", "vision"]
license = "MIT"
version = "0.40.0"
edition = "2018"
authors = ["Mathieu Poumeyrol <kali@zoy.org>", "Pro <twisted.fall@gmail.com>"]

[lib]
doctest = false

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = ["binding-generator"]

[dependencies]
libc = "0.2"
num-traits = "0.2"
once_cell = "1.0"

[features]
default = ["opencv-4"]
buildtime-bindgen = ["binding-generator", "clang", "jobserver"]
clang-runtime = ["binding-generator/clang-runtime"]
opencv-32 = []
opencv-34 = []
opencv-4 = []
contrib = []
docs-only = []

[build-dependencies]
binding-generator = {package = "opencv-binding-generator", version = "0.13", path = "binding-generator", optional = true}
cc = {version = "1.0", features = ["parallel"]}
clang = {version = "0.23", features = ["clang_6_0"], optional = true}
glob_crate = {package = "glob", version = "0.3"}
jobserver = {version = "0.1", optional = true}
once_cell = "1.0"
pkg-config = "0.3"
semver = "0.10"
shlex = "0.1"
vcpkg = "0.2"

[dev-dependencies]
matches = "0.1"

[package.metadata.docs.rs]
features = ["docs-only", "contrib"]
