[package]
name = "opencv"
description = "Rust bindings for OpenCV"
documentation = "http://www.poumeyrol.fr/doc/opencv-rust/opencv/index.html"
repository = "https://github.com/kali/opencv-rust"
readme = "README.md"
keywords = [ "opencv", "vision" ]
license = "MIT"
version = "0.4.0"
edition = "2018"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.14"
cc = "1.0"
glob = "0.3"
